package io.aegis.android.core

import android.content.Context
import android.content.SharedPreferences
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import kotlinx.serialization.json.Json

/**
 * Production [VaultStore] backed by Android Keystore + SharedPreferences.
 *
 * On first save, generates a non-extractable AES-256-GCM key in the
 * Android Keystore (alias [KEY_ALIAS]). On subsequent saves, reuses
 * that key. The vault JSON is encrypted under that key and the
 * resulting (iv || ciphertext) is base64-encoded into SharedPreferences.
 *
 * Why we add a Keystore wrap on top of the already-encrypted vault:
 *   - The vault is encrypted under a passphrase-derived key (PBKDF2
 *     → AES-GCM). Without device binding, an attacker who copied the
 *     SharedPreferences file could attempt offline brute-force against
 *     the passphrase.
 *   - The Keystore key is non-extractable: it never leaves the secure
 *     hardware (or, on devices without StrongBox, the OS process). To
 *     decrypt the vault file, the attacker must have the device itself
 *     unlocked. Mirrors aegis-apple's
 *     `kSecAttrAccessibleWhenUnlockedThisDeviceOnly`.
 *
 * We don't use AndroidX `EncryptedSharedPreferences` (Google
 * deprecated `androidx.security:security-crypto` in 2024) — using the
 * Keystore directly keeps the dep footprint smaller and gives full
 * control over key parameters.
 */
internal class KeystoreVaultStore(context: Context) : VaultStore {

    private val prefs: SharedPreferences =
        context.applicationContext.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)

    private val json: Json = Json {
        // Permissive: vaults written by aegis-web or aegis-apple may
        // include fields we don't yet model in this PR (e.g., future
        // schema additions); we want to load them without crashing.
        ignoreUnknownKeys = true
        encodeDefaults = true
    }

    override fun save(persisted: PersistedIdentity) {
        try {
            val plaintext = json.encodeToString(PersistedIdentity.serializer(), persisted)
                .encodeToByteArray()
            val key = getOrCreateKey()
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.ENCRYPT_MODE, key)
            val ct = cipher.doFinal(plaintext)
            // Prefix the IV so we can recover it on read. AES-GCM IV
            // length isn't a fixed property of the cipher object — it's
            // generated by `init(...)` when no spec is provided, and we
            // pull it back via `cipher.iv`.
            val iv = cipher.iv
            require(iv != null && iv.size == VaultCrypto.IV_BYTES) {
                "unexpected IV length ${iv?.size}"
            }
            val combined = iv + ct
            val encoded = java.util.Base64.getEncoder().encodeToString(combined)
            prefs.edit().putString(BLOB_KEY, encoded).apply()
        } catch (e: VaultError) {
            throw e
        } catch (e: Exception) {
            throw VaultError.StorageFailure("save failed: ${e.message ?: e::class.simpleName}", e)
        }
    }

    override fun load(): PersistedIdentity? {
        val encoded = prefs.getString(BLOB_KEY, null) ?: return null
        try {
            val combined = java.util.Base64.getDecoder().decode(encoded)
            require(combined.size > VaultCrypto.IV_BYTES) { "stored blob too short" }
            val iv = combined.copyOfRange(0, VaultCrypto.IV_BYTES)
            val ct = combined.copyOfRange(VaultCrypto.IV_BYTES, combined.size)
            val key = getOrCreateKey()
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(
                Cipher.DECRYPT_MODE,
                key,
                GCMParameterSpec(VaultCrypto.TAG_BITS, iv),
            )
            val plaintext = cipher.doFinal(ct).decodeToString()
            return json.decodeFromString(PersistedIdentity.serializer(), plaintext)
        } catch (e: VaultError) {
            throw e
        } catch (e: Exception) {
            throw VaultError.StorageFailure(
                "load failed: ${e.message ?: e::class.simpleName}",
                e,
            )
        }
    }

    override fun delete() {
        try {
            prefs.edit().remove(BLOB_KEY).apply()
            // Also drop the Keystore key so the next save starts fresh
            // — otherwise the old key lingers indefinitely.
            val ks = KeyStore.getInstance(ANDROID_KEYSTORE)
            ks.load(null)
            if (ks.containsAlias(KEY_ALIAS)) ks.deleteEntry(KEY_ALIAS)
        } catch (e: Exception) {
            throw VaultError.StorageFailure(
                "delete failed: ${e.message ?: e::class.simpleName}",
                e,
            )
        }
    }

    // -----------------------------------------------------------------------
    // Key management
    // -----------------------------------------------------------------------

    private fun getOrCreateKey(): SecretKey {
        val ks = KeyStore.getInstance(ANDROID_KEYSTORE)
        ks.load(null)
        (ks.getEntry(KEY_ALIAS, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }

        val gen = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
        gen.init(
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                // We do NOT require user authentication on the Keystore
                // key — the user-presence check happens at the *unlock
                // method* layer (passphrase / passkey). Adding it here
                // would force a biometric prompt for every save (e.g.
                // when adding a new unlock method), which is ergonomically
                // wrong.
                .setUserAuthenticationRequired(false)
                .build()
        )
        return gen.generateKey()
    }

    private companion object {
        const val ANDROID_KEYSTORE = "AndroidKeyStore"
        const val KEY_ALIAS = "io.aegis.android.vault.kek"
        const val PREFS_NAME = "io.aegis.android.vault"
        const val BLOB_KEY = "v2-vault-singleton"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
    }
}
